export const ALL_HIRE_REQUEST_REQUEST = "ALL_HIRE_REQUEST_REQUEST";
export const ALL_HIRE_REQUEST_SUCCESS = "ALL_HIRE_REQUEST_SUCCESS";
export const ALL_HIRE_REQUEST_FAIL = "ALL_HIRE_REQUEST_FAIL";

export const ADMIN_HIRE_REQUEST_REQUEST = "ADMIN_HIRE_REQUEST_REQUEST";
export const ADMIN_HIRE_REQUEST_SUCCESS = "ADMIN_HIRE_REQUEST_SUCCESS";
export const ADMIN_HIRE_REQUEST_FAIL = "ADMIN_HIRE_REQUEST_FAIL";

export const USER_HIRE_REQUEST_REQUEST = "NEW_HIRE_REQUEST_REQUEST";
export const USER_HIRE_REQUEST_SUCCESS = "NEW_HIRE_REQUEST_SUCCESS";
export const USER_HIRE_REQUEST_FAIL = "USER_HIRE_REQUEST_FAIL";

export const UPDATE_HIRE_REQUEST_REQUEST = "UPDATE_HIRE_REQUEST_REQUEST";
export const UPDATE_HIRE_REQUEST_SUCCESS = "UPDATE_HIRE_REQUEST_SUCCESS";
export const UPDATE_HIRE_REQUEST_FAIL = "UPDATE_HIRE_REQUEST_FAIL";

export const DELETE_HIRE_REQUEST_REQUEST = "DELETE_HIRE_REQUEST_REQUEST";
export const DELETE_HIRE_REQUEST_SUCCESS = "DELETE_HIRE_REQUEST_SUCCESS";
export const DELETE_HIRE_REQUEST_FAIL = "DELETE_HIRE_REQUEST_FAIL";

export const HIRE_REQUEST_DETAILS_REQUEST = "HIRE_REQUEST_DETAILS_REQUEST";
export const HIRE_REQUEST_DETAILS_SUCCESS = "HIRE_REQUEST_DETAILS_SUCCESS";
export const HIRE_REQUEST_DETAILS_FAIL = "HIRE_REQUEST_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
