export const POST_HIRING_REQUEST_REQUEST = "POST_HIRING_REQUEST_REQUEST";
export const POST_HIRING_REQUEST_SUCCESS = "POST_HIRING_REQUEST_SUCCESS";
export const POST_HIRING_REQUEST_FAIL = "POST_HIRING_REQUEST_FAILED";
