export const POST_SERVICE_REQUEST_REQUEST = "POST_SERVICINGREQUEST_REQUEST";
export const POST_SERVICE_REQUEST_SUCCESS = "POST_SERVICINGREQUEST_SUCCESS";
export const POST_SERVICE_REQUEST_FAIL = "POST_SERVICING_REQUEST_FAILED";
